# This workflow will build a NanoVMs unikernel package and publish it to repo.ops.city

name: nanovms-bind

# Controls when the workflow will run
on: workflow_dispatch # manual trigger for now

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: sudo apt install -y pkg-config libtool autoconf libuv1-dev libnghttp2-dev libssl make

      - name: Clone stable BIND9
        run: git clone --branch v9_18 https://gitlab.isc.org/isc-projects/bind9.git
        
      - name: autoconf 
        run: cd bind9 && autoreconf -fi

      - name: configure
        run: pwd
